wso2/docker-is

dockerfile/Dockerfile
dockerfile/README.md

Update the README on building the IS docker image and running the container. Also include instructions on how to modify configs of the IS instance using a volume mount. Related to #14.

Update README on building the docker image and running the container. 

---

dockerfiles/is-analytics/README.md
dockerfiles/is/README.md

> It is required to improve README.md files by providing Docker as an installation prerequisite.
> Improve README.md files by providing Docker as an installation prerequisite.

Add Docker as a prerequisite to README.md files

---

dockerfiles/is-analytics/README.md
dockerfiles/is/README.md

> It is required to improve the README.md documentation to provide clear instructions to user.
> Improves the README.md documentation

Improve the README.md documentation

---

docker-compose/is-analytics/docker-compose.yml

Specify dockerhub.wso2.com as the docker registry when pulling image for docker-compose.

Pull images from dockerhub.wso2.com for docker-compose

---

docker-compose/is-analytics/README.md
docker-compose/is-analytics/docker-compose.yml
dockerfiles/is-analytics/Dockerfile
dockerfiles/is-analytics/README.md
dockerfiles/is/Dockerfile
dockerfiles/is/README.md

> fixes #41 
> MySQL connector jar is added via the Dockerfile. Since Docker Docker image already contains the MySQL connector, mounting MySQL connector in Docker-compose is removed.

Add MySQL connector via Dockerfile 

---

docker-compose/IS-with-Analytics/README.md
docker-compose/IS-with-Analytics/docker-compose.yml

> Change **dockerhub.wso2.com** domain to **docker.wso2..com**
fixes #46

Add Docker registry Domain

---

dockerfiles/is-analytics/README.md
dockerfiles/is/README.md

> Change version from 5.4.1 to 5.5.0

Fix version in readme

---

docker-compose/IS-with-Analytics/docker-compose.yml
docker-compose/IS-with-Analytics/identity-server/repository/conf/carbon.xml
dockerfiles/is-analytics/Dockerfile
dockerfiles/is-analytics/init.sh
dockerfiles/is/Dockerfile
dockerfiles/is/init.sh

> Prepare Identity Server and Identity Server Analytics profile Docker images for clustering. This fixes https://github.com/wso2/docker-is/issues/58.
> Prepare Identity Server and Identity Server Analytics profile Docker images for clustering.

Prepare Identity Server and Identity Server Analytics profile Docker images for clustering

---

.gitignore
docker-compose/IS-with-Analytics/docker-compose.yml
docker-compose/IS-with-Analytics/identity-server/repository/conf/carbon.xml
dockerfiles/is-analytics/Dockerfile
dockerfiles/is-analytics/init.sh
dockerfiles/is/Dockerfile
dockerfiles/is/init.sh

> Merge 5.5.x branch to master branch - 14/06/2018

Merge 5.5.x branch to master branch

---

docker-compose/is-with-analytics/docker-compose.yml
dockerfiles/is-analytics/init.sh
dockerfiles/is/init.sh

> Rename configuration mount folder in product containers from `volumes` to `wso2-server-volume`.
> Rename configuration mount folder in product containers with a meaningful name.

Rename configuration mount folder in product containers

---

.gitignore
dockerfiles/alpine/Dockerfile
dockerfiles/alpine/README.md
dockerfiles/alpine/init.sh

> Generate the alpine docker files for IS
> Generate the alpine docker files for IS

Alpine dockerfiles for IS version 5.5.x

---

CHANGELOG.md
README.md

Add change log

---

dockerfiles/alpine/is-analytics/README.md
dockerfiles/alpine/is/README.md
dockerfiles/centos/is-analytics/README.md
dockerfiles/centos/is/README.md
dockerfiles/ubuntu/is-analytics/README.md
dockerfiles/ubuntu/is/README.md

> Revise the readme file 
> Readme file was changed to reflect the files that were changed for Ubuntu,centos and alpine dockerfiles

Revise readme file

---

dockerfiles/ubuntu/is/Dockerfile
dockerfiles/ubuntu/is/README.md
dockerfiles/ubuntu/is/init.sh

Improve Ubuntu IS v5.5.x Docker resource structure and documentation

Improve Ubuntu IS v5.5.x Docker resource structure and documentation

---

dockerfiles/alpine/is/Dockerfile
dockerfiles/alpine/is/README.md
dockerfiles/alpine/is/init.sh
dockerfiles/centos/is/Dockerfile
dockerfiles/centos/is/README.md
dockerfiles/centos/is/init.sh

>Changes to Dockerfile , Readme and Init.sh
> Changes to Dockerfile , Readme and Init.sh

Change readme, init.sh and dockerfiles for centos and alpine for IS

---

README.md

5.5.x main readme update

---

CHANGELOG.md
README.md
dockerfiles/alpine/is-analytics/Dockerfile
dockerfiles/alpine/is-analytics/init.sh
dockerfiles/alpine/is/Dockerfile
dockerfiles/alpine/is/README.md
dockerfiles/alpine/is/init.sh
dockerfiles/centos/is-analytics/Dockerfile
dockerfiles/centos/is-analytics/init.sh
dockerfiles/centos/is/Dockerfile
dockerfiles/centos/is/README.md
dockerfiles/centos/is/init.sh
dockerfiles/ubuntu/is-analytics/Dockerfile
dockerfiles/ubuntu/is-analytics/init.sh

> Refinements to Dockerfiles and Docker image entrypoint scripts. Further, adds missing improvements to support introducing additional configuration changes and artifacts during container based deployments in WSO2 Identity Server Analytics v5.5.x Alpine Docker resources. This fixes https://github.com/wso2/docker-is/issues/89.
> Refinements to Dockerfiles and Docker image entrypoint scripts.

Refinements to Dockerfiles and Docker image entrypoint scripts

---

dockerfiles/alpine/is-analytics/Dockerfile
dockerfiles/alpine/is-analytics/README.md
dockerfiles/alpine/is-analytics/init.sh
dockerfiles/alpine/is/Dockerfile
dockerfiles/alpine/is/README.md
dockerfiles/alpine/is/init.sh
dockerfiles/centos/is-analytics/Dockerfile
dockerfiles/centos/is-analytics/README.md
dockerfiles/centos/is-analytics/init.sh
dockerfiles/centos/is/README.md
dockerfiles/centos/is/init.sh
dockerfiles/ubuntu/is-analytics/Dockerfile
dockerfiles/ubuntu/is-analytics/README.md
dockerfiles/ubuntu/is-analytics/init.sh
dockerfiles/ubuntu/is/README.md
dockerfiles/ubuntu/is/init.sh

> Fix README documentation and Docker resource comments.
> Fix README documentation and Docker resource comments.

Fix README documentation and Docker resource comments

---

dockerfiles/alpine/is-analytics/Dockerfile
dockerfiles/alpine/is-analytics/init.sh
dockerfiles/centos/is-analytics/init.sh
dockerfiles/ubuntu/is-analytics/init.sh

> Add MOTD to Alpine IS-Analytics Dockerfile.
> Add MOTD to Alpine IS-Analytics Dockerfile.

Add MOTD to Alpine IS-Analytics Dockerfile

---

dockerfiles/alpine/is-analytics/Dockerfile
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is-analytics/Dockerfile
dockerfiles/ubuntu/is-analytics/Dockerfile

Update copy paths in dockerfiles

Update copy paths in dockerfiles

---

dockerfiles/alpine/is-analytics/init.sh
dockerfiles/alpine/is/init.sh
dockerfiles/centos/is-analytics/init.sh
dockerfiles/centos/is/init.sh

> Swap mounts in entrypoint scripts.
> Swap mounts in entrypoint scripts.

Swap mounts in entrypoint scripts

---

CHANGELOG.md

> Fix change log spelling mistake.
> Fix change log spelling mistake.

Fix change log spelling mistake

---

dockerfiles/centos/is-analytics/Dockerfile
dockerfiles/centos/is/Dockerfile

> Change netcat tool to install in centos docker images
> Change the netcat tool to resolve bug:https://github.com/wso2/docker-is/issues/96

change netcat tool to install in centos docker images

---

CHANGELOG.md
README.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/alpine/is/README.md
dockerfiles/centos/is/Dockerfile
dockerfiles/centos/is/README.md
dockerfiles/ubuntu/is/Dockerfile
dockerfiles/ubuntu/is/README.md

> Introduced a crypto-tool utility to the <CARBON_HOME>/bin directory to encrypt the secondary userstore password.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A

Introduced a crypto-tool utility

---

CHANGELOG.md
README.md
docker-compose/is-with-analytics/scripts/README.md

> Fix README documentation and finalize the change log.
> Fix README documentation and finalize the change log

Fix README documentation

---

docker-compose/is-with-analytics/docker-compose.yml

Fix test command in health check to use the new password.

Fix MySQL healthcheck test command

---

docker-compose/is-with-analytics/docker-compose.yml

Add persistent volume to survive docker container recreation

Add persistent volumes for mysql

---

CHANGELOG.md
CONTRIBUTING.md
README.md
docker-compose/is-with-analytics/docker-compose.yml
dockerfiles/alpine/is-analytics/dashboard/Dockerfile
dockerfiles/alpine/is-analytics/worker/Dockerfile
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is-analytics/dashboard/Dockerfile
dockerfiles/centos/is-analytics/worker/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/ubuntu/is-analytics/dashboard/Dockerfile
dockerfiles/ubuntu/is-analytics/worker/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

> Merge 5.8.x branch with master branch - 2019-08-28.
> Merge 5.8.x branch with master branch

Merge 5.8.x branch with master branch - 2019-08-28

---

dockerfiles/alpine/is-analytics/dashboard/Dockerfile
dockerfiles/alpine/is-analytics/worker/Dockerfile
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is-analytics/dashboard/Dockerfile
dockerfiles/centos/is-analytics/worker/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/ubuntu/is-analytics/dashboard/Dockerfile
dockerfiles/ubuntu/is-analytics/worker/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

Fix Mysql jar download URL

---

CHANGELOG.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

Change the remote location for downloading the MySQL connector jar.
>  Fixes #183

Fix MySQL connector jar Download URL

---

CHANGELOG.md
README.md

> Add change log for release v5.10.0.2
> Add change log for release v5.10.0.2

Add change log for release v5.10.0.2

---

CHANGELOG.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

fixed the issue https://github.com/wso2/docker-is/issues/208 by upgrading the JDK to latest for each base OS platform

Upgrade JDK to latest for each base OS platform

---

CHANGELOG.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

> This PR addresses $subject. Thus, it fixes https://github.com/wso2/docker-is/issues/211.
> Package the latest version of Kubernetes Membership Scheme

[v5.10.x] Package the latest version of Kubernetes Membership Scheme

---

CHANGELOG.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

> This PR merges `5.10.x` branch to the `master` branch.
> Merge `5.10.x` branch to the master branch

Merge 5.10.x branch to the master branch - 2020-07-22

---

CHANGELOG.md
README.md

> This PR performs $subject for release tag `v5.10.0.3`.
> Update CHANGELOG documentation

[v5.10.x] Update CHANGELOG documentation

---

CHANGELOG.md
CONTRIBUTING.md
README.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/alpine/is/README.md
dockerfiles/centos/is/Dockerfile
dockerfiles/centos/is/README.md
dockerfiles/ubuntu/is/Dockerfile
dockerfiles/ubuntu/is/README.md

> This PR performs $subject fixing the linked issue.
> Introduce Docker Resources for Identity Server version `5.11.0`
> Docker Engine Community version `19.03.5` (both client and server)

[5.11.0] Introduce Docker Resources for Identity Server

---

dockerfiles/alpine/is/README.md
dockerfiles/centos/is/README.md
dockerfiles/ubuntu/is/README.md

> This PR performs $subject with details of new management consoles of Identity Server version `5.11.0`, fixing the linked issue.
> Update README documentation with details of Identity Server consoles

[5.11.0] Update README Documentation

---

CHANGELOG.md

> Create release for docker-is 5.7.0.4

[5.7.0] Update CHANGELOG for the latest release(5.7.0.4)

---

CHANGELOG.md

> Create release for docker-is 5.8.0.5

[5.8.0] Update CHANGELOG for the latest release(5.8.0.5)

---

CHANGELOG.md

> Create release for docker-is 5.9.0.4

[5.9.0] Update CHANGELOG for the latest release(5.9.0.4)

---

CHANGELOG.md

> Create release for docker-is 5.10.0.4

[5.10.0] Update CHANGELOG for the latest release(5.10.0.4)

---

CHANGELOG.md

> Create release for docker-is 5.6.0.2

[5.6.0] Update CHANGELOG for the latest release(5.6.0.2)

---

CHANGELOG.md

> [5.10.0] Update the release date

[5.10.0] Update the release date

---

CHANGELOG.md

> [5.9.0] Update the release date

[5.9.0] Update the release date

---

CHANGELOG.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

> Rebase 5.10.x to Master branch
> Update master branch

Rebase 5.10.x to Master branch

---

CHANGELOG.md

> [5.8.0] Update the release date

[5.8.0] Update the release date

---

CHANGELOG.md

> [5.7.0] Update the release date

[5.7.0] Update the release date

---

CHANGELOG.md

> [5.6.0] Update the release date

[5.6.0] Update the release date

---

CHANGELOG.md

> [5.5.0] Update the release date

[5.5.0] Update the release date

---

CHANGELOG.md
README.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

> Merge `5.10.x` branch to `master` branch - 2020/11/27
> Merge `5.10.x` branch to `master` branch

Merge 5.10.x branch to master branch

---

CHANGELOG.md

Update the WSO2 IAM 5.11.0 release date in Change log

Update the change log with release date

---

CHANGELOG.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

Fix high-security vulnerability issue by upgrading the base image. 
https://github.com/wso2/docker-is/issues/271

Update ubuntu base image to fix vulnerability issue

---

CHANGELOG.md
dockerfiles/ubuntu/is/Dockerfile

Update change-log with current release details

Update change-log with current release details

---

CHANGELOG.md

Update changelog with current release details.

Update changelog with current release details

---

docker-compose/is/docker-compose.yml
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile

Sync 5.110 branch with Master branch

---

dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

With the PR https://github.com/wso2/kubernetes-common/pull/21, we released  k8s common v1.0.8 and this PR we are going o commit the change.

Update k8s common version

---

CHANGELOG.md

Update change log for 5.11.0.3 release

---

dockerfiles/alpine/is/README.md
dockerfiles/centos/is/README.md
dockerfiles/ubuntu/is/README.md

> Instructions given on how to build docker images with a different UID from the default one.
https://github.com/wso2/docker-is/issues/286
https://github.com/wso2/product-is/issues/12181

UID update tip added to dockerfile README.md

---

dockerfiles/alpine/is/README.md
dockerfiles/centos/is/README.md
dockerfiles/ubuntu/is/README.md

> Instructions given on how to build docker images with a different UID from the default one.
https://github.com/wso2/docker-is/issues/286
https://github.com/wso2/product-is/issues/12181

UID and GID update tip added to dockerfile README.md

---

dockerfiles/alpine/is/README.md
dockerfiles/centos/is/README.md
dockerfiles/ubuntu/is/README.md

Revert "UID update tip added to dockerfile README.md"

---

CHANGELOG.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

Resolve https://github.com/wso2/docker-is/issues/299

Update base image to cater vulnerabilities

---

dockerfiles/jdk11/alpine/is/Dockerfile

Bump the alpine version 

---

CHANGELOG.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/alpine/is/README.md
dockerfiles/alpine/is/docker-entrypoint.sh
dockerfiles/centos/is/Dockerfile
dockerfiles/centos/is/README.md
dockerfiles/centos/is/docker-entrypoint.sh
dockerfiles/jdk11/alpine/is/Dockerfile
dockerfiles/jdk11/centos/is/Dockerfile
dockerfiles/jdk8/alpine/is/Dockerfile
dockerfiles/jdk8/centos/is/Dockerfile
dockerfiles/jdk8/ubuntu/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile
dockerfiles/ubuntu/is/README.md
dockerfiles/ubuntu/is/docker-entrypoint.sh

> Support backward comfortability by adding alpine, ubuntu, centos dockerfiles to dockerfilies directory.

[5.11.x] Add alpine, ubuntu and centos dockerfiles to dockerfiles directory for backward comfortability.

---

CHANGELOG.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/alpine/is/README.md
dockerfiles/alpine/is/docker-entrypoint.sh
dockerfiles/centos/is/Dockerfile
dockerfiles/centos/is/README.md
dockerfiles/centos/is/docker-entrypoint.sh
dockerfiles/jdk11/centos/is/Dockerfile
dockerfiles/jdk8/alpine/is/Dockerfile
dockerfiles/jdk8/centos/is/Dockerfile
dockerfiles/jdk8/ubuntu/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile
dockerfiles/ubuntu/is/README.md
dockerfiles/ubuntu/is/docker-entrypoint.sh

> Support backward comfortability by adding alpine, ubuntu, centos dockerfiles to dockerfilies directory.

Add alpine, ubuntu and centos dockerfiles to dockerfiles directory for backward comfortability.

---

CHANGELOG.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/alpine/is/README.md
dockerfiles/alpine/is/docker-entrypoint.sh
dockerfiles/centos/is/Dockerfile
dockerfiles/centos/is/README.md
dockerfiles/centos/is/docker-entrypoint.sh
dockerfiles/jdk11/alpine/is/Dockerfile
dockerfiles/jdk11/centos/is/Dockerfile
dockerfiles/jdk11/ubuntu/is/Dockerfile
dockerfiles/jdk8/alpine/is/Dockerfile
dockerfiles/jdk8/ubuntu/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile
dockerfiles/ubuntu/is/README.md
dockerfiles/ubuntu/is/docker-entrypoint.sh

> Support backward comfortability by adding alpine, ubuntu, centos dockerfiles to dockerfilies directory.

[5.10.x] Add alpine, ubuntu and centos dockerfiles to dockerfiles directory for backward comfortability.

---

dockerfiles/ubuntu/is/Dockerfile

Add Ubuntu base image and add Adoptium JDK jdk-11.0.13+8 to reduce the issues introduced by the base image.

Add Ubuntu base image and add Adoptium JDK jdk-11.0.13+8

---

dockerfiles/jdk11/ubuntu/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

Updated the release tag to v5.10.0.10.

Update release tag

---

CHANGELOG.md
dockerfiles/ubuntu/is-analytics/dashboard/Dockerfile
dockerfiles/ubuntu/is-analytics/worker/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

**Add Ubuntu 20.04 base image and add Adoptium OpenJDK8U-jdk_x64_linux_hotspot_8u312b07 to the base image  to reduce the issues introduced by the IS-KM 5.7.0 base image.** 
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus …

Add ubuntu20.04 base image in IS and IS-analytics 5.8.0

---

CHANGELOG.md
dockerfiles/alpine/is/Dockerfile

Upgrade alpine base image version to 3.15.4.

[5.11.x] Bump alpine base image to v3.15.4

---

CHANGELOG.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/jdk8/alpine/is/Dockerfile

Change alpine base image to 3.15

[5.11.x] Change alpine base image to 3.15

---

CHANGELOG.md
dockerfiles/centos/is-analytics/dashboard/Dockerfile
dockerfiles/centos/is-analytics/worker/Dockerfile

[5.8.x][IS-Analytics] Update analytics centos version

---

CHANGELOG.md
docker-compose/is/dockerfiles/is/Dockerfile
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/jdk8/alpine/is/Dockerfile
dockerfiles/jdk8/centos/is/Dockerfile
dockerfiles/jdk8/ubuntu/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

> Bump mysql connector version from v8.0.17 to v8.0.29
- https://github.com/wso2/docker-is/issues/339

[Master]Bump mysql connector version

---

CHANGELOG.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/jdk8/alpine/is/Dockerfile
dockerfiles/jdk8/centos/is/Dockerfile
dockerfiles/jdk8/ubuntu/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

[5.11.x] Update alpine base docker image version to 3.16

---

dockerfiles/centos/is/Dockerfile
dockerfiles/centos/is/README.md
dockerfiles/centos/is/docker-entrypoint.sh

>This PR adds Centos Docker file

Add centos

---

dockerfiles/alpine/is/README.md
dockerfiles/centos/is/README.md
dockerfiles/ubuntu/is/README.md

>This PR updates the master branch readme files.

Address comments

---

CHANGELOG.md

Update changelog for 5.11.0.17 release

---

CHANGELOG.md
CONTRIBUTING.md
README.md
docker-compose/is/README.md
docker-compose/is/conf/identity-server/repository/conf/deployment.toml
docker-compose/is/conf/mysql/scripts/mysql_identity.sql
docker-compose/is/dockerfiles/is/Dockerfile
dockerfiles/alpine/is/Dockerfile
dockerfiles/alpine/is/README.md
dockerfiles/centos/is/Dockerfile
dockerfiles/centos/is/README.md
dockerfiles/ubuntu/is/Dockerfile
dockerfiles/ubuntu/is/README.md

> This PR updates for wso2is-6.1.0 release

Update master for 6.1.0 release

---

CHANGELOG.md
CONTRIBUTING.md
README.md
docker-compose/is/README.md
docker-compose/is/conf/identity-server/repository/conf/deployment.toml
docker-compose/is/conf/mysql/scripts/mysql_identity.sql
docker-compose/is/dockerfiles/is/Dockerfile
dockerfiles/alpine/is/Dockerfile
dockerfiles/alpine/is/README.md
dockerfiles/centos/is/Dockerfile
dockerfiles/centos/is/README.md
dockerfiles/ubuntu/is/Dockerfile
dockerfiles/ubuntu/is/README.md

> This PR modifies wget logic in the docker file to handle 6.1.x updates.

Update 6.1.x docker file

---

CHANGELOG.md

updated the GA release date

---

dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

> $subject
> https://github.com/wso2/docker-is/pull/367

Edit comments added

---

CHANGELOG.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

> Bump kubernetes membership schema version to 1.0.11

[5.7.0] Bump kube membership schema version

---

CHANGELOG.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

Bump the JDK version to latest - 11.0.19
Related Issue: https://github.com/wso2-enterprise/wso2-iam-internal/issues/585

Upgrade jdk version

---

CHANGELOG.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

> Upgrade jdk version to 11.0.20.1
- https://github.com/wso2-enterprise/wso2-iam-internal/issues/886

[5.11] Upgrade jdk version

---

CHANGELOG.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

> Upgrade jdk version to 11.0.20.1
- https://github.com/wso2-enterprise/wso2-iam-internal/issues/886

[6.0] Upgrade jdk version

---

CHANGELOG.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

> Upgrade jdk version to 11.0.20.1
- https://github.com/wso2-enterprise/wso2-iam-internal/issues/886

[6.1] Upgrade jdk version

---

dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/jdk8/alpine/is/Dockerfile
dockerfiles/jdk8/centos/is/Dockerfile
dockerfiles/jdk8/ubuntu/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

> upgrade the k8 version to 1.0.11

Upgrade k8 version to 1.0.11

---

CHANGELOG.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

[IS 6.1.0] Update Alpine based Docker Image Version to 3.16

---

CHANGELOG.md
dockerfiles/jdk17/alpine/is/Dockerfile
dockerfiles/jdk17/alpine/is/README.md
dockerfiles/jdk17/alpine/is/docker-entrypoint.sh
dockerfiles/jdk17/centos/is/Dockerfile
dockerfiles/jdk17/centos/is/README.md
dockerfiles/jdk17/centos/is/docker-entrypoint.sh
dockerfiles/jdk17/ubuntu/is/Dockerfile
dockerfiles/jdk17/ubuntu/is/README.md
dockerfiles/jdk17/ubuntu/is/docker-entrypoint.sh

Add JDK 17 6.1.0 dockerfiles

---

dockerfiles/jdk17/alpine/is/Dockerfile

[6.1] Update java version

---

dockerfiles/jdk17/alpine/is/Dockerfile

[7.0] Update java version

---

dockerfiles/jdk17/alpine/is/Dockerfile

Update java version

---

dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

$subject
- https://github.com/wso2/product-is/issues/18981
- https://github.com/wso2/docker-is/pull/402

[IS-5.9] Remove unused ARG K8S_MEMBERSHIP_SCHEME_VERSION

---

dockerfiles/jdk17/alpine/is/Dockerfile

$subject
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …

update JDK 17 version to 17.0.10

---

README.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/jdk17/alpine/is/Dockerfile
dockerfiles/jdk17/centos/is/Dockerfile
dockerfiles/jdk17/ubuntu/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

[7.0.x] Remove third party JDBC connector from base docker image

---

README.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/jdk17/alpine/is/Dockerfile
dockerfiles/jdk17/centos/is/Dockerfile
dockerfiles/jdk17/ubuntu/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

[Master] Remove third party JDBC connector from base docker image

---

README.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/jdk17/alpine/is/Dockerfile
dockerfiles/jdk17/centos/is/Dockerfile
dockerfiles/jdk17/ubuntu/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

[6.1.x] Remove third party JDBC connector from base docker image

---

README.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

[6.0.x] Remove third party JDBC connector from base docker image

---

README.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/jdk8/alpine/is/Dockerfile
dockerfiles/jdk8/centos/is/Dockerfile
dockerfiles/jdk8/ubuntu/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

[5.11.x] Remove third party JDBC connector from base docker image

---

README.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/jdk8/alpine/is/Dockerfile
dockerfiles/jdk8/centos/is/Dockerfile
dockerfiles/jdk8/ubuntu/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

[5.10.x] Remove third party JDBC connector from base docker image

---

README.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

[5.9.x] Remove third party JDBC connector from base docker image

---

README.md
dockerfiles/alpine/is-analytics/dashboard/Dockerfile
dockerfiles/alpine/is-analytics/worker/Dockerfile
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is-analytics/dashboard/Dockerfile
dockerfiles/centos/is-analytics/worker/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/ubuntu/is-analytics/dashboard/Dockerfile
dockerfiles/ubuntu/is-analytics/worker/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

[5.8.x] Remove third party JDBC connector from base docker image

---

README.md
dockerfiles/alpine/is-analytics/dashboard/Dockerfile
dockerfiles/alpine/is-analytics/worker/Dockerfile
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is-analytics/dashboard/Dockerfile
dockerfiles/centos/is-analytics/worker/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/ubuntu/is-analytics/dashboard/Dockerfile
dockerfiles/ubuntu/is-analytics/worker/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

[5.7.x] Remove third party JDBC connector from base docker image

---

dockerfiles/jdk17/rocky/is/Dockerfile
dockerfiles/jdk17/rocky/is/README.md
dockerfiles/jdk17/rocky/is/docker-entrypoint.sh
dockerfiles/rocky/is/Dockerfile
dockerfiles/rocky/is/README.md
dockerfiles/rocky/is/docker-entrypoint.sh

[6.1.0] Add rocky linux docker image for IS 6.1.0

---

dockerfiles/rocky/is/Dockerfile
dockerfiles/rocky/is/README.md
dockerfiles/rocky/is/docker-entrypoint.sh

[6.0.0] Add rocky linux docker image for IS 6.0.0

---

dockerfiles/jdk8/rocky/is/Dockerfile
dockerfiles/jdk8/rocky/is/README.md
dockerfiles/jdk8/rocky/is/docker-entrypoint.sh
dockerfiles/rocky/is/Dockerfile
dockerfiles/rocky/is/README.md
dockerfiles/rocky/is/docker-entrypoint.sh

[5.11.0] Add rocky linux docker image for IS 5.11.0

---

dockerfiles/jdk8/rocky/is/Dockerfile
dockerfiles/jdk8/rocky/is/README.md
dockerfiles/jdk8/rocky/is/docker-entrypoint.sh
dockerfiles/rocky/is/Dockerfile
dockerfiles/rocky/is/README.md
dockerfiles/rocky/is/docker-entrypoint.sh

[5.10.0] Add rocky linux docker image for IS 5.10.0

---

dockerfiles/rocky/is/Dockerfile
dockerfiles/rocky/is/README.md
dockerfiles/rocky/is/docker-entrypoint.sh

[5.9.0] Add rocky linux docker image for IS 5.9.0

---

dockerfiles/rocky/is-analytics/dashboard/Dockerfile
dockerfiles/rocky/is-analytics/dashboard/README.md
dockerfiles/rocky/is-analytics/dashboard/docker-entrypoint.sh
dockerfiles/rocky/is-analytics/worker/Dockerfile
dockerfiles/rocky/is-analytics/worker/README.md
dockerfiles/rocky/is-analytics/worker/docker-entrypoint.sh
dockerfiles/rocky/is/Dockerfile
dockerfiles/rocky/is/README.md
dockerfiles/rocky/is/docker-entrypoint.sh

[5.8.0] Add rocky linux docker image for IS and IS analytics 5.8.0

---

dockerfiles/rocky/is-analytics/dashboard/Dockerfile
dockerfiles/rocky/is-analytics/dashboard/README.md
dockerfiles/rocky/is-analytics/dashboard/docker-entrypoint.sh
dockerfiles/rocky/is-analytics/worker/Dockerfile
dockerfiles/rocky/is-analytics/worker/README.md
dockerfiles/rocky/is-analytics/worker/docker-entrypoint.sh
dockerfiles/rocky/is/Dockerfile
dockerfiles/rocky/is/README.md
dockerfiles/rocky/is/docker-entrypoint.sh

[5.7.0] Add rocky linux docker image for IS and IS analytics 5.7.0

---

dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/jdk8/alpine/is/Dockerfile
dockerfiles/jdk8/centos/is/Dockerfile
dockerfiles/jdk8/rocky/is/Dockerfile
dockerfiles/jdk8/ubuntu/is/Dockerfile
dockerfiles/rocky/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

[5.11.0] Update dns-java version to 3.6.1

---

dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/jdk8/alpine/is/Dockerfile
dockerfiles/jdk8/centos/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

[IS 5.10.0] Add java link for arm64

---

dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/jdk8/alpine/is/Dockerfile
dockerfiles/jdk8/centos/is/Dockerfile
dockerfiles/jdk8/rocky/is/Dockerfile
dockerfiles/jdk8/ubuntu/is/Dockerfile
dockerfiles/rocky/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

> subject
**Related PR**
- https://github.com/wso2/docker-is/pull/430

Bump docker release to 5.10.0.22

---

dockerfiles/ubuntu/is/Dockerfile

[6.1] Update release tag

---

dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/jdk17/alpine/is/Dockerfile
dockerfiles/jdk17/centos/is/Dockerfile
dockerfiles/jdk17/ubuntu/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

Upgrade dns-java version to 3.6.1

---

CHANGELOG.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/jdk17/alpine/is/Dockerfile
dockerfiles/jdk17/centos/is/Dockerfile
dockerfiles/jdk17/rocky/is/Dockerfile
dockerfiles/jdk17/ubuntu/is/Dockerfile
dockerfiles/rocky/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

$subject
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …

[IS 6.1.0] Update Alpine based Docker Image Version to 3.20.3

---

CHANGELOG.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/jdk17/alpine/is/Dockerfile
dockerfiles/jdk17/centos/is/Dockerfile
dockerfiles/jdk17/rocky/is/Dockerfile
dockerfiles/jdk17/ubuntu/is/Dockerfile
dockerfiles/rocky/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

[IS 7.0] Update Alpine based Docker Image Version to v3.20.3

---

CHANGELOG.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/rocky/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

[IS 6.0] Update Alpine based Docker Image Version to v3.20.3

---

CHANGELOG.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/jdk8/alpine/is/Dockerfile
dockerfiles/jdk8/centos/is/Dockerfile
dockerfiles/jdk8/rocky/is/Dockerfile
dockerfiles/jdk8/ubuntu/is/Dockerfile
dockerfiles/rocky/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

[IS 5.11] Update Alpine based Docker Image Version to v3.20.3

---

dockerfiles/alpine/is/docker-entrypoint.sh
dockerfiles/jdk17/alpine/is/docker-entrypoint.sh

$Subject
- https://github.com/wso2-enterprise/wso2-iam-internal/issues/2974

Fix warn logs due to permission issues in the Alpine docker Images

---

dockerfiles/alpine/is/docker-entrypoint.sh
dockerfiles/jdk17/alpine/is/docker-entrypoint.sh

$Subject
- https://github.com/wso2-enterprise/wso2-iam-internal/issues/2974

[7.0] Fix warn logs due to permission issues in the Alpine docker Image

---

CHANGELOG.md

Update IS 7.1.0 change log

---

CHANGELOG.md
dockerfiles/alpine/is/Dockerfile
dockerfiles/centos/is/Dockerfile
dockerfiles/jdk17/alpine/is/Dockerfile
dockerfiles/jdk17/centos/is/Dockerfile
dockerfiles/jdk17/rocky/is/Dockerfile
dockerfiles/jdk17/ubuntu/is/Dockerfile
dockerfiles/rocky/is/Dockerfile
dockerfiles/ubuntu/is/Dockerfile

- Upgrade jdk version to 17.0.15+6

[IS 6.1] Upgrade jdk version

---

dockerfiles/jdk11/alpine/is/Dockerfile
dockerfiles/jdk11/rocky/is/Dockerfile
dockerfiles/jdk11/ubuntu/is/Dockerfile

Upgrade JDK-11 version to jdk-11.0.27+6

---

dockerfiles/jdk17/ubuntu/is/Dockerfile

Update Ubuntu base version to 24.04 in JDK17 docker file
