dockerfile/README.md
Change docker image tag from wso2is-5.3.0 to wso2is:5.3.0 and refine content in the IS Dockerfile README.md file.
=> Update docker image tag and refine content in dockerfile README.md

README.md, dockerfiles/is-analytics/Dockerfile, dockerfiles/is/Dockerfile
> It is required to define user id and group id for the non-root user in a Dockerfile for permission management during volume mounting from Docker host to containers. In addition, the README.md files required refinements. This resolves https://github.com/wso2/docker-is/issues/31.
> Introduce user id and group id for the non-root user in Dockerfiles and refine README.md documentation.
=> Define user id and group id for non-root users in Dockerfiles

docker-compose/is-analytics/docker-compose.yml
The `is-analytics` docker compose project fails to start up because the analytics container is spawned before the mysql container is ready. Hence we increase the health check interval for mysql in order to ensure the server is up and also ready to accept connections. Fix #33.
=> Increase mysql health check interval in docker-compose 

dockerfiles/is/Dockerfile, dockerfiles/is/README.md
The setup instructions were incomplete, so clarified them, and adjusted the Dockerfile to not require additional downloads.
Have a first-run experience through the IS README without errors.
N/A
As a user, I want to run the Identity Server through Docker (without having to [sign up for a trial](https://wso2.com/identity-and-access-management/install/download/?type=docker)).
* Fixed setup instructions for the Identity Server Docker image
It's in the pull request.
N/A?
N/A
N/A
N/A
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? no
- Ran FindSecurityBugs plugin and verified report? no
N/A
none
none
```
$ ls files
jdk1.8.0_172 …
```
=> fix IS instructions

dockerfiles/alpine/is-analytics/base/Dockerfile, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is-analytics/base/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/ubuntu/is-analytics/base/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
> Defined MOTD as an ARG with a default message(WUM UPDATED). For a GA build pass MOTD as a build ARG.
Ex: `docker build -t image_name:tag --build-arg MOTD=$MESSAGE .`
fixes #112 
fixes #111
=> Add MOTD as an ARG

dockerfiles/alpine/is-analytics/README.md, dockerfiles/alpine/is-analytics/base/Dockerfile, dockerfiles/alpine/is-analytics/dashboard/Dockerfile, dockerfiles/alpine/is-analytics/dashboard/init.sh, dockerfiles/alpine/is-analytics/worker/Dockerfile, dockerfiles/alpine/is-analytics/worker/init.sh, dockerfiles/alpine/is/Dockerfile, dockerfiles/alpine/is/README.md, dockerfiles/alpine/is/init.sh, dockerfiles/centos/is-analytics/README.md, dockerfiles/centos/is-analytics/base/Dockerfile, dockerfiles/centos/is-analytics/dashboard/Dockerfile, dockerfiles/centos/is-analytics/dashboard/init.sh, dockerfiles/centos/is-analytics/worker/Dockerfile, dockerfiles/centos/is-analytics/worker/init.sh, dockerfiles/centos/is/Dockerfile, dockerfiles/centos/is/README.md, dockerfiles/centos/is/init.sh, dockerfiles/ubuntu/is-analytics/README.md, dockerfiles/ubuntu/is-analytics/base/Dockerfile, dockerfiles/ubuntu/is-analytics/dashboard/Dockerfile, dockerfiles/ubuntu/is-analytics/dashboard/init.sh, dockerfiles/ubuntu/is-analytics/worker/Dockerfile, dockerfiles/ubuntu/is-analytics/worker/init.sh, dockerfiles/ubuntu/is/Dockerfile, dockerfiles/ubuntu/is/README.md, dockerfiles/ubuntu/is/init.sh
> It is suggested to use AdoptOpenJDK 8 based Docker images for WSO2 Identity Server and related products. This PR fixes https://github.com/wso2/docker-is/issues/117, fixes https://github.com/wso2/docker-is/issues/118, fixes https://github.com/wso2/docker-is/issues/120 and fixes https://github.com/wso2/docker-is/issues/122.
> Use AdoptOpenJDK in Alpine, CentOS and Ubuntu based Docker images.
=> Use AdoptOpenJDK 8 in WSO2 Identity Server and related product Docker resources

.metadata, docker-compose/is-with-analytics/identity-server/repository/conf/carbon.xml, docker-compose/is-with-analytics/identity-server/repository/conf/identity/identity.xml
> It was identified that configuration file changes exist between WSO2 Identity Server v5.8.0 RC-1 and RC-3. These need to be integrated for the WSO2 Identity Server with Analytics Docker Compose based deployment.
> Integrate differences between WSO2 Identity Server v5.8.0 RC-1 and RC-3
=> Integrate differences between WSO2 Identity Server v5.8.0 RC-1 and RC-3

docker-compose/is-with-analytics/docker-compose.yml, docker-compose/is-with-analytics/scripts/README.md, docker-compose/is-with-analytics/scripts/deploy.sh
> Integrate support in Docker Compose resources for usage of both types of users: users with and without WSO2 subscriptions. Currently, only users with WSO2 subscriptions can utilize Docker Compose resources. This fixes https://github.com/wso2/docker-is/issues/136.
> Integrate support in Docker Compose resources for users with and without WSO2 subscriptions
=> Integrate support in Docker Compose resources for users with and without WSO2 subscriptions

dockerfiles/alpine/is-analytics/dashboard/Dockerfile, dockerfiles/alpine/is-analytics/worker/Dockerfile, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is-analytics/dashboard/Dockerfile, dockerfiles/centos/is-analytics/worker/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/ubuntu/is-analytics/dashboard/Dockerfile, dockerfiles/ubuntu/is-analytics/worker/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
> Use WSO2 product pack downloadable links to binaries available at JFrog Bintray. This fixes https://github.com/wso2/docker-is/issues/153.
> Use WSO2 product pack downloadable links to binaries available at JFrog Bintray
=> Use WSO2 product pack downloadable links to binaries available at JFrog Bintray

dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
> Add artifacts required for WSO2 Kubernetes membership scheme to Identity Server Docker resources. This fixes https://github.com/wso2/docker-is/issues/160.
> Package the Kubernetes Membership Scheme in WSO2 Identity Server Docker images
=> Add artifacts required for WSO2 Kubernetes membership scheme to Identity Server Docker resources

dockerfiles/alpine/is-analytics/dashboard/Dockerfile, dockerfiles/alpine/is-analytics/worker/Dockerfile, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is-analytics/dashboard/Dockerfile, dockerfiles/centos/is-analytics/worker/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/ubuntu/is-analytics/dashboard/Dockerfile, dockerfiles/ubuntu/is-analytics/worker/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
> This PR upgrades the MySQL JDBC connector to latest version. This fixes https://github.com/wso2/docker-is/issues/119.
> Upgrade MySQL JDBC connector to latest version
=> Upgrade MySQL JDBC Connector version from 5.1.47 to 8.0.17

CHANGELOG.md, README.md, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
> It is required to update the WSO2 Kubernetes Membership Scheme to the latest `v1.0.7` [1]. This fixes https://github.com/wso2/docker-is/issues/177.
>
> [1]: [Release tag](https://github.com/wso2/kubernetes-common/releases/tag/v1.0.7)
> [v5.8.x] Package the latest version of Kubernetes Membership Scheme in WSO2 Identity Server Docker images.
=> [v5.8.x] Package the latest version of Kubernetes Membership Scheme in WSO2 Identity Server Docker images

dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
- Updated to OpenJDK 11.0.7_10
Allow joining Kubernetes 1.16 clusters.
Closing #201
Updated to OpenJDK 11.0.7_10 which fixes [JDK-8236039](https://bugs.openjdk.java.net/browse/JDK-8236039) and allows joining Kubernetes 1.16 clusters.
#201
Upgraded to OpenJDK 11.0.7_10
Not sure what automated tests are in place for Docker that may be affected
wso2/kubernetes-is#221
=> Updated to OpenJDK 11.0.7, Closes #201

.gitignore, CHANGELOG.md, dockerfiles/alpine/is-analytics/Dockerfile, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is-analytics/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
This PR includes the changes for the IS 5.5.0 Dockerfiles which compatible with Jenkins automated process.
- Remove logic of copying the JDK and product pack from the file directory
- Add MYSQL JDBC connector, version 5.1.49
- In the current docker image build process, it is instructed to copy the relevant JDK, Product pack and the MySQL JDBC connector to the file directory and in the Dockerfile it's copying the files from the file directory. In order to compatible with WSO2 Docker image create automation process, this has been changed to get the product pack from WUM, JDK from the Jenkins and MySQL from the maven central repository.
https://github.com/wso2/docker-is/issues/212
=> [5.5.0]Change scripts to compatible with jenkins process

dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
> This PR introduces the Docker source Git release tag as a label. This fixes #220  
> Introduce the Docker source Git release tag as a label. 
> Use the dockerfile instruction `LABEL` to add Git release tag as a label.
> Client: Docker Engine - Community
Server: Docker Engine - Community
Engine:
Built:            Mon Jun 22 15:44:07 2020
OS/Arch:          linux/amd64
Experimental:     false
containerd:
Version:          1.2.13
GitCommit: …
=> [5.10.0] Add Git release tag as a label

dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
> This PR enables SSL verification for `wget`. This fixes #219 
> Enable SSL verification for `wget`.
> Removes existing option `--no-check-certificate` for `wget`. 
> Client: Docker Engine - Community
Server: Docker Engine - Community
Engine:
Built:            Mon Jun 22 15:44:07 2020
OS/Arch:          linux/amd64
Experimental:     false
containerd:
Version:          1.2.13
GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
runc:
Version: …
=> [5.10.0] Enable SSL verification for wget

dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
> This PR introduces the Docker source Git release tag as a label and enable SSL verification for `wget`. This fixes #224, #223  
> Introduce the Docker source Git release tag as a label. 
Enable SSL verification for `wget`.
> Use the dockerfile instruction `LABEL` to add Git release tag as a label.
Removes existing option --no-check-certificate for `wget`.
>Client: Docker Engine - Community
>Server: Docker Engine - Community
Engine:
Built: …
=> [5.9.0] Add Git release tag as a label & enable SSL cert verification for wget 

dockerfiles/alpine/is-analytics/dashboard/Dockerfile, dockerfiles/alpine/is-analytics/worker/Dockerfile, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is-analytics/dashboard/Dockerfile, dockerfiles/centos/is-analytics/worker/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/ubuntu/is-analytics/dashboard/Dockerfile, dockerfiles/ubuntu/is-analytics/worker/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
> This PR introduces the Docker source Git release tag as a label and enable SSL verification for wget. This fixes #227 , #228 
> Introduce the Docker source Git release tag as a label.
> Enable SSL verification for wget.
> Use the dockerfile instruction LABEL to add Git release tag as a label.
> Removes existing option --no-check-certificate for wget.
> Client: Docker Engine - Community
> Server: Docker Engine - Community
Engine:
Built:            Mon …
=> [5.8.0] Add Git release tag as a label and enable SSL verification for wget

dockerfiles/alpine/is-analytics/dashboard/Dockerfile, dockerfiles/alpine/is-analytics/worker/Dockerfile, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is-analytics/dashboard/Dockerfile, dockerfiles/centos/is-analytics/worker/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/ubuntu/is-analytics/dashboard/Dockerfile, dockerfiles/ubuntu/is-analytics/worker/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
> This PR introduces the Docker source Git release tag as a label and enable SSL verification for wget. This fixes #230, #231  
> Introduce the Docker source Git release tag as a label.
> Enable SSL verification for wget.
> Use the dockerfile instruction LABEL to add Git release tag as a label.
> Removes existing option --no-check-certificate for wget.
> Client: Docker Engine - Community
> Server: Docker Engine - Community
Engine:
Built:            Mon …
=> [5.7.0] Add Git release tag as a label and enable SSL verification for wget

CHANGELOG.md, README.md, dockerfiles/alpine/is/Dockerfile, dockerfiles/alpine/is/README.md, dockerfiles/centos/is/Dockerfile, dockerfiles/centos/is/README.md, dockerfiles/ubuntu/is/Dockerfile, dockerfiles/ubuntu/is/README.md
> This PR covers $subject thus, fixing the linked issue.
>
> Also, it removes the creation of Java preferences directory which as earlier introduced to fix the following warning.
> ```
> WARN — FileSystemPreferences Could not lock System prefs. Unix error code 0.
> WARN — FileSystemPreferences Couldn’t Flush system prefs: > java.util.prefs.BackingStoreException: Couldn’t get file lock.
> ```
> Avoid packaging MySQL JDBC driver in Identity Server Docker images
> Docker Engine Community version `19.03.5` (both client and server)
=> [5.11.0] Avoid packaging MySQL JDBC driver in Identity Server Docker images

CHANGELOG.md
> Create release for docker-is 5.5.0.9
=> [5.5.0] Update CHANGELOG for the latest release(5.5.0.9)

CHANGELOG.md, README.md, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
> This PR performs $subject. This fixes https://github.com/wso2/docker-is/issues/261.
> Upgrade AdoptOpenJDK 11 version to the latest version - 11.0.9_11-jdk (2020/11/27)
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Docker Engine Community version `19.03.5` (both client and server)
=> [5.10.0] Upgrade AdoptOpenJDK 11 version to the latest version - 11.0.9_11-jdk

dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile
This PR updates the below base version of IS-5.11.0 docker images
- Alpine: adoptopenjdk/openjdk11:jdk-11.0.10_9-alpine
- Centos: adoptopenjdk/openjdk11:x86_64-centos-jdk-11.0.10_9
=> Update Docker base image of IS 5.11.0 Docker images

CHANGELOG.md, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
**Syncing 5.11.x to master **
With the PR wso2/kubernetes-common#21, we released k8s common v1.0.8 and this PR we are going o commit the change here: https://github.com/wso2/docker-is/pull/289
Test - docker build with the fix (alphine)
=> Update k8s common version

CHANGELOG.md, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
Resolves https://github.com/wso2/docker-is/issues/302
=> Update base image to cater vulnerabilities 

CHANGELOG.md, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/jdk8/alpine/is/Dockerfile, dockerfiles/jdk8/centos/is/Dockerfile, dockerfiles/jdk8/ubuntu/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
Changed the dockerfiles to have a base OS image with JDK installed on top of it, instead of directly importing a jdk installed image. Furthermore, brought the dockerfiles to a common format according to what was done in https://github.com/wso2/docker-is/pull/316 and https://github.com/wso2/docker-is/pull/318. 
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes/no
https://github.com/wso2/docker-is/pull/318 
https://github.com/wso2/docker-is/pull/316
=> Modified Dockerfiles to have OS based base image and adoptium JDK 8 and 11

CHANGELOG.md, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/jdk8/alpine/is/Dockerfile, dockerfiles/jdk8/centos/is/Dockerfile, dockerfiles/jdk8/ubuntu/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
Changed the dockerfiles to have a base OS image with JDK installed on top of it, instead of directly importing a jdk installed image. Furthermore, brought the dockerfiles to a common format according to what was done in https://github.com/wso2/docker-is/pull/316 and https://github.com/wso2/docker-is/pull/318. 
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes/no
https://github.com/wso2/docker-is/pull/318 
https://github.com/wso2/docker-is/pull/316
=> [5.11.x] Modified Dockerfiles to have OS based base image and adoptium JDK 8 and 11 for IS 

CHANGELOG.md, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/jdk8/alpine/is/Dockerfile, dockerfiles/jdk8/centos/is/Dockerfile, dockerfiles/jdk8/ubuntu/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
Changed the dockerfiles to have a base OS image with JDK installed on top of it, instead of directly importing a jdk installed image. Furthermore, brought the dockerfiles to a common format according to what was done in https://github.com/wso2/docker-is/pull/316 and https://github.com/wso2/docker-is/pull/318. 
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes/no
https://github.com/wso2/docker-is/pull/318 
https://github.com/wso2/docker-is/pull/316
=> [5.10.x] Modified Dockerfiles to have OS based base image and adoptium JDK 8 and 11 for IS

CHANGELOG.md, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
Changed the dockerfiles to have a base OS image with JDK installed on top of it, instead of directly importing a jdk installed image. Furthermore, brought the dockerfiles to a common format according to what was done in https://github.com/wso2/docker-is/pull/316 and https://github.com/wso2/docker-is/pull/318. 
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes/no
https://github.com/wso2/docker-is/pull/318 
https://github.com/wso2/docker-is/pull/316
=> [5.9] Modified Dockerfiles to have OS based base image and adoptium JDK 8

CHANGELOG.md, docker-compose/is/dockerfiles/is/Dockerfile, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/jdk8/alpine/is/Dockerfile, dockerfiles/jdk8/centos/is/Dockerfile, dockerfiles/jdk8/ubuntu/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
> Bump mysql connector version from v8.0.17 to v8.0.29
- https://github.com/wso2/docker-is/issues/339
=> [5.11.x]Bump mysql connector version

CHANGELOG.md, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
> Bump mysql connector version from v8.0.17 to v8.0.29
- https://github.com/wso2/docker-is/issues/339
=> [5.9.x] Bump mysql connector version

CHANGELOG.md, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/jdk8/alpine/is/Dockerfile, dockerfiles/jdk8/centos/is/Dockerfile, dockerfiles/jdk8/ubuntu/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
> Bump mysql connector version from v8.0.17 to v8.0.29
- https://github.com/wso2/docker-is/issues/339
=> [5.10.x] Bump mysql connector version

dockerfiles/jdk8/alpine/is/Dockerfile
> Forcefully install glibc in jdk8 alpine image.
=> Forcefully install glibc in alpine 3.16

dockerfiles/ubuntu/is/Dockerfile
> Current docker file only supports amd64 architecture only. This change allows the user to build is 6.0.0 docker image in arm64 architecture too.
=> Provide docker image support for ARM based architecture

CHANGELOG.md, dockerfiles/ubuntu/is-analytics/dashboard/Dockerfile, dockerfiles/ubuntu/is-analytics/worker/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
Add Ubuntu 20.04 base image and add Adoptium OpenJDK8U-jdk_x64_linux_hotspot_8u312b07 to the base image to reduce the issues introduced by the IS 5.7.0 and IS-analytics 5.7.0 base image.
=> [IS-5.7.0] Update IS and IS-analytics to Ubuntu 20.04

CHANGELOG.md, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/jdk8/alpine/is/Dockerfile, dockerfiles/jdk8/centos/is/Dockerfile, dockerfiles/jdk8/ubuntu/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
Upgrade jdk-11.0.14+9 to jdk-11.0.18+10 and jdk8u322-b06 to jdk8u362-b09 to mitigate known vulnerabilities.
=> [5.11] Upgrade java versions

CHANGELOG.md, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
Upgrade jdk-11.0.14+9 and jdk-11.0.13+8 to jdk-11.0.18+10 to mitigate known vulnerabilities.
=> [6.0] Upgrade java versions

CHANGELOG.md, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
Upgrade jdk-11.0.14+9 and jdk-11.0.13+8 to jdk-11.0.18+10 to mitigate known vulnerabilities.
=> Upgrade java versions

CHANGELOG.md, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
Upgrade jdk-11.0.14+9 and jdk-11.0.13+8 to jdk-11.0.18+10 to mitigate known vulnerabilities.
=> [6.1] Upgrade java versions

CHANGELOG.md, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/jdk8/alpine/is/Dockerfile, dockerfiles/jdk8/centos/is/Dockerfile, dockerfiles/jdk8/ubuntu/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
Upgrade jdk-11.0.14+9 and jdk-11.0.13+8 to jdk-11.0.18+10 and jdk8u322-b06 to jdk8u362-b09 to mitigate known vulnerabilities.
=> [5.10] Upgrade java versions

CHANGELOG.md, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
Bump the JDK version to latest - 11.0.19
Related Issue: https://github.com/wso2-enterprise/wso2-iam-internal/issues/585
=> [5.11.0] Update jdk version

CHANGELOG.md, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
Bump the JDK version to latest - 11.0.19
Related Issue: https://github.com/wso2-enterprise/wso2-iam-internal/issues/585
=> [6.0.0] Update jdk version

CHANGELOG.md, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
Bump the JDK version to latest - 11.0.19
Related Issue: https://github.com/wso2-enterprise/wso2-iam-internal/issues/585
=> [6.1.0] Update JDK version

dockerfiles/alpine/is/README.md, dockerfiles/centos/is/README.md
- Some places in readme docs, mention IS version as `5.11` and with this PR, it s corrected by replacing it with `6.1`.
=> [IS 6.1.0] Fix Readme Doc Issue

dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/jdk8/alpine/is/Dockerfile, dockerfiles/jdk8/centos/is/Dockerfile, dockerfiles/jdk8/ubuntu/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
$subject
With hazelcast upgrade from 3.x to 5.x , we have moved the KubernetesMembershipScheme class from kubernetes-common to the kernel. As a result, adding the [kubernetes-membership-scheme-1.x.x.jar](https://github.com/wso2/kubernetes-common/tags) to the product is not required any more.
=> [IS-5.10] Remove kubernetes-membership-scheme jar

dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
$subject
With hazelcast upgrade from 3.x to 5.x , we have moved the KubernetesMembershipScheme class from kubernetes-common to the kernel. As a result, adding the [kubernetes-membership-scheme-1.x.x.jar](https://github.com/wso2/kubernetes-common/tags) to the product is not required any more.
=> [IS-5.9] Remove k8 membership scheme

dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/jdk8/alpine/is/Dockerfile, dockerfiles/jdk8/centos/is/Dockerfile, dockerfiles/jdk8/ubuntu/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
$subject
With hazelcast upgrade from 3.x to 5.x , we have moved the KubernetesMembershipScheme class from kubernetes-common to the kernel. As a result, adding the [kubernetes-membership-scheme-1.x.x.jar](https://github.com/wso2/kubernetes-common/tags) to the product is not required any more.
=> [5.11] Remove k8 membership scheme

dockerfiles/jdk17/rocky/is/Dockerfile, dockerfiles/jdk17/rocky/is/README.md, dockerfiles/jdk17/rocky/is/docker-entrypoint.sh, dockerfiles/rocky/is/Dockerfile, dockerfiles/rocky/is/README.md, dockerfiles/rocky/is/docker-entrypoint.sh
=> [7.0.0] Add rocky linux docker image for IS 7.0

dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/rocky/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
> This PR addresses the security vulnerabilities related to the `jackson-databind` library in the WSO2 Identity Server Docker images by removing `K8S_MEMBERSHIP_SCHEME_VERSION`.
> Resolve the identified security vulnerabilities by eliminating the dependency on outdated versions of `kubernetes-common`.
1. Verified the vulnerability in versions 1.0.9 and 1.0.10 of `kubernetes-common` and identified that version 1.0.11 uses a secure `jackson-databind` version.
2. Cloned the `wso2/docker-is` repository and identified the usage of `K8S_MEMBERSHIP_SCHEME_VERSION`.
3. Removed the `K8S_MEMBERSHIP_SCHEME_VERSION` from relevant Dockerfiles.
4. Built and tested the updated Docker images in a Kubernetes environment to ensure no disruption in functionality.
- JDK Versions: JDK 11
- Operating Systems: …
=> Remove K8S_MEMBERSHIP_SCHEME_VERSION to Address Jackson-databind Vulnerabilities in Docker Images

dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/jdk8/alpine/is/Dockerfile, dockerfiles/jdk8/centos/is/Dockerfile, dockerfiles/jdk8/rocky/is/Dockerfile, dockerfiles/jdk8/ubuntu/is/Dockerfile, dockerfiles/rocky/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
- Upgrade the dnsjava version from 2.1.8 to 3.6.1 to  fix the vulnerability in dns java 2.1.8 version
=> Upgrade dns java to 3.6.1 version

CHANGELOG.md, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/jdk8/alpine/is/Dockerfile, dockerfiles/jdk8/centos/is/Dockerfile, dockerfiles/jdk8/rocky/is/Dockerfile, dockerfiles/jdk8/ubuntu/is/Dockerfile, dockerfiles/rocky/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
=> [IS 5.10] Update Alpine based Docker Image Version to v3.20.3

dockerfiles/ubuntu/is/Dockerfile
- Upgrade the ubuntu base image version to 24.04 version
- use netcat-openbsd instead of netcat because netcat is removed from ubuntu 24.04 and alternatives are netcat-traditional and netcat-openbsd.
- use netcat-openbsd because in  in ubuntu 20.04 also using the netcat-openbsd with another version when installing it using netcat.
- netcat and the netcat-openbsd has the same arguments with the `nc` command.
=> Upgrade ubuntu base image version to 24.04

dockerfiles/jdk8/alpine/is/Dockerfile
Upgrade glibc version to 2.35-r1 to address https://github.com/sgerrand/alpine-pkg-glibc/issues/185.
- https://github.com/sgerrand/alpine-pkg-glibc/issues/185
=> [5.10.x] Upgrade glibc version to 2.35-r1

dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/jdk17/alpine/is/Dockerfile, dockerfiles/jdk17/centos/is/Dockerfile, dockerfiles/jdk17/ubuntu/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
$subject
With hazelcast upgrade from 3.x to 5.x , we have moved the KubernetesMembershipScheme class from kubernetes-common to the kernel. As a result, adding the [kubernetes-membership-scheme-1.x.x.jar](https://github.com/wso2/kubernetes-common/tags) to the product is not required any more.
Related PRs:
- https://github.com/wso2/docker-is/pull/415
- https://github.com/wso2/docker-is/pull/404
=> [master] Remove k8 membership scheme

dockerfiles/pqc/is/Dockerfile, dockerfiles/pqc/is/README.md, dockerfiles/pqc/is/docker-entrypoint.sh
Create a separate docker file with Post Quantum TLS enabled by default
- JDK 21
- Ubuntu 24.04
=> Add docker files for WSO2 IS with Post-Quantum TLS support

CHANGELOG.md, dockerfiles/alpine/is/Dockerfile, dockerfiles/centos/is/Dockerfile, dockerfiles/jdk8/alpine/is/Dockerfile, dockerfiles/jdk8/centos/is/Dockerfile, dockerfiles/jdk8/rocky/is/Dockerfile, dockerfiles/jdk8/ubuntu/is/Dockerfile, dockerfiles/rocky/is/Dockerfile, dockerfiles/ubuntu/is/Dockerfile
- Upgrade the Alpine base image to v3.20.6
- Update jdk-11.0.20.1+1 to jdk-11.0.27+6 for Alpine, Rocky and Ubuntu
> Note : Centos JDK-11 update is not performed as it is now deprecated. 
> The release tag was updated to `5.11.0.26` as a version with `5.11.0.25` was already released.
=> Upgrade the Alpine base image to v3.20.6 and bump the JDK 11 version.
